// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpVe19nUBpDaeTpwjqrNd1vNGkw724h3c',
    appId: '1:742980597076:web:a956e5f5cab8eb372ac4c1',
    messagingSenderId: '742980597076',
    projectId: 'abaimind',
    authDomain: 'abaimind.firebaseapp.com',
    storageBucket: 'abaimind.firebasestorage.app',
    measurementId: 'G-S8HQ1T7NRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDM4gOX6BKvMevNMwjQ3p2f_40AUEjjMk',
    appId: '1:742980597076:android:fcab7f7ea08c21972ac4c1',
    messagingSenderId: '742980597076',
    projectId: 'abaimind',
    storageBucket: 'abaimind.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0bKAm9RcFun8b5qhhsHaxAJ4_5S2gidg',
    appId: '1:742980597076:ios:78b1e7ab4b35fcc32ac4c1',
    messagingSenderId: '742980597076',
    projectId: 'abaimind',
    storageBucket: 'abaimind.firebasestorage.app',
    iosClientId: '742980597076-hdlq8c7irq56jolnkut2is92eesjqeg2.apps.googleusercontent.com',
    iosBundleId: 'com.example.abaimind',
  );
}
